---
exclude: '(venv|.vscode)'  # regex
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: remove-tabs
        exclude_types: [makefile, binary]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.24.2
    hooks:
      - id: yamllint
  - repo: https://github.com/danielhoherd/pre-commit-hooks
    rev: 07f5a00b0f7d7856d602baf5e530a4d4472d7bf3
    hooks:
      - id: remove-unicode-non-breaking-spaces
      - id: remove-unicode-zero-width-non-breaking-spaces
      - id: remove-en-dashes
      - id: sort-gitignore
